# Generated by Django 5.0.7 on 2024-11-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_address_product_user_delete_productaddress'),
        ('product', '0002_product_image'),
    ]

    operations = [
    ]
