# Generated by Django 5.0.7 on 2024-11-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_date_of_birth_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
